require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DefectsController do

  # This should return the minimal set of attributes required to create a valid
  # Defect. As you add validations to Defect, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all defects as @defects" do
      defect = Defect.create! valid_attributes
      get :index, {}, valid_session
      assigns(:defects).should eq([defect])
    end
  end

  describe "GET show" do
    it "assigns the requested defect as @defect" do
      defect = Defect.create! valid_attributes
      get :show, {:id => defect.to_param}, valid_session
      assigns(:defect).should eq(defect)
    end
  end

  describe "GET new" do
    it "assigns a new defect as @defect" do
      get :new, {}, valid_session
      assigns(:defect).should be_a_new(Defect)
    end
  end

  describe "GET edit" do
    it "assigns the requested defect as @defect" do
      defect = Defect.create! valid_attributes
      get :edit, {:id => defect.to_param}, valid_session
      assigns(:defect).should eq(defect)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Defect" do
        expect {
          post :create, {:defect => valid_attributes}, valid_session
        }.to change(Defect, :count).by(1)
      end

      it "assigns a newly created defect as @defect" do
        post :create, {:defect => valid_attributes}, valid_session
        assigns(:defect).should be_a(Defect)
        assigns(:defect).should be_persisted
      end

      it "redirects to the created defect" do
        post :create, {:defect => valid_attributes}, valid_session
        response.should redirect_to(Defect.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved defect as @defect" do
        # Trigger the behavior that occurs when invalid params are submitted
        Defect.any_instance.stub(:save).and_return(false)
        post :create, {:defect => { "title" => "invalid value" }}, valid_session
        assigns(:defect).should be_a_new(Defect)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Defect.any_instance.stub(:save).and_return(false)
        post :create, {:defect => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested defect" do
        defect = Defect.create! valid_attributes
        # Assuming there are no other defects in the database, this
        # specifies that the Defect created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Defect.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => defect.to_param, :defect => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested defect as @defect" do
        defect = Defect.create! valid_attributes
        put :update, {:id => defect.to_param, :defect => valid_attributes}, valid_session
        assigns(:defect).should eq(defect)
      end

      it "redirects to the defect" do
        defect = Defect.create! valid_attributes
        put :update, {:id => defect.to_param, :defect => valid_attributes}, valid_session
        response.should redirect_to(defect)
      end
    end

    describe "with invalid params" do
      it "assigns the defect as @defect" do
        defect = Defect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Defect.any_instance.stub(:save).and_return(false)
        put :update, {:id => defect.to_param, :defect => { "title" => "invalid value" }}, valid_session
        assigns(:defect).should eq(defect)
      end

      it "re-renders the 'edit' template" do
        defect = Defect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Defect.any_instance.stub(:save).and_return(false)
        put :update, {:id => defect.to_param, :defect => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested defect" do
      defect = Defect.create! valid_attributes
      expect {
        delete :destroy, {:id => defect.to_param}, valid_session
      }.to change(Defect, :count).by(-1)
    end

    it "redirects to the defects list" do
      defect = Defect.create! valid_attributes
      delete :destroy, {:id => defect.to_param}, valid_session
      response.should redirect_to(defects_url)
    end
  end

end
